language: node_js
node_js:
  - 10
  - node
env:
  - DEFAULT_NODE_VERSION=10

before_script:
  - PUBLIC_URL=https://ldflex.github.io/Solid-Playground/ yarn build

after_success:
  - if [ "$TRAVIS_NODE_VERSION" == "$DEFAULT_NODE_VERSION" ]; then
      ./.travis_build_pages;
    fi

cache: yarn
